version: "3.9"

networks:
  app-spring-angular:
    driver: bridge
volumes:
  data:

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Ngochung1809!
      - MYSQL_DATABASE=angular_spring
    networks:
      - app-spring-angular
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"
  backend:
    build:
      context: ./BackEnd-SpringBoot/
      dockerfile: Dockerfile
    image: ngochung1809/back-end-app-spring:latest
    networks:
      - app-spring-angular
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/angular_spring
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Ngochung1809!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=8080
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8888/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8888:8080"
    depends_on:
      - db
  frontend:
    build:
      context: ./FrontEnd-Angular/
      dockerfile: Dockerfile
    image: ngochung1809/nginx-app-spring:latest
    networks:
      - app-spring-angular
    ports:
      - "80:80"
    depends_on:
      - db
      - backend
    

