version: "3.9"

networks:
  app-spring-angular:
    driver: bridge
volumes:
  data:
  # grafana_config:
  # grafana_data:
  # grafana_logs:

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Ngochung1809!
      - MYSQL_DATABASE=angular_spring
    networks:
      - app-spring-angular
    volumes:
      - data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build:
      context: ./BackEnd-SpringBoot/
      dockerfile: Dockerfile
    image: ngochung1809/back-end-app-spring:latest
    networks:
      - app-spring-angular
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/angular_spring
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=Ngochung1809!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SERVER_PORT=8080
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build:
      context: ./FrontEnd-Angular/
      dockerfile: Dockerfile
    image: ngochung1809/nginx-app-spring:latest
    networks:
      - app-spring-angular
    ports:
      - "80:80"
    depends_on:
      - db
      - backend
      
  # prometheus:
  #   image: prom/prometheus:latest
  #   ports:
  #   - 9090:9090
  #   networks:
  #     - app-spring-angular
  #   volumes:
  #   - "./prometheus.yml:/etc/prometheus/prometheus.yml"
  #   depends_on:
  #     - db
  #     - backend
  #     - frontend
          
  # loki:
  #   image: grafana/loki:2.8.0
  #   container_name: loki
  #   volumes:
  #     - ./loki-config.yaml:/mnt/config/loki-config.yaml
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - app-spring-angular
  #   command: -config.file=/mnt/config/loki-config.yaml
  #   depends_on:
  #     - db
  #     - backend
  #     - frontend

  # promtail:
  #   image: grafana/promtail:2.8.0
  #   container_name: promtail
  #   volumes:
  #     - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
  #     - /var/log:/var/log
  #   networks:
  #     - app-spring-angular
  #   links:
  #     - loki
  #   command: -config.file=/mnt/config/promtail-config.yaml
  #   depends_on:
  #     - db
  #     - backend
  #     - frontend

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - app-spring-angular
  #   volumes:
  #     - grafana_config:/etc/grafana
  #     - grafana_data:/var/lib/grafana
  #     - grafana_logs:/var/log/grafana
  #   depends_on:
  #     - db
  #     - backend
  #     - frontend
    

