spring:
  application:
    name: employee-app
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create-drop}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/employee_app}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:Ngochung1809!}
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${SERVER_PORT:8080}
